version: '3.8'

services:
  app:
    image: hugfiles:3
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - celery
    environment:
      - EMAIL_TEST=prueba@mail.com
      - PORT=5000
      - FLASK_ENV=development
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - UPLOAD_FOLDER=data/files
  celery:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: ["celery", "worker", "-A", "app.celery", "--loglevel=info"]
  redis:
    image: redis:6.2.5-alpine